const translations = {
  tr: {
    'nav.about': 'Hakkında',
    'nav.dates': 'Tarihler',
    'nav.topics': 'Konular',
    'nav.publication': 'Yayın Olanakları',
    'nav.registration': 'Katılım',
    'nav.boards': 'Kurullar',
    'nav.rules': 'Yazım Kuralları',
    'nav.contact': 'İletişim',
    'hero.eyebrow': 'Hibrit Akademik Konferans',
    'hero.title': 'III. Uluslararası Yaşam Kalitesi Konferansı',
    'hero.subtitle': 'Yaşam kalitesi kavramını disiplinlerarası bir çerçevede ele alan, Türkçe ve İngilizce bildirilere açık uluslararası konferans.',
    'hero.dateLabel': 'Tarih',
    'hero.dateValue': '16–17 Ocak 2026',
    'hero.locationLabel': 'Yer',
    'hero.locationValue': 'Çanakkale / Türkiye',
    'hero.modeLabel': 'Format',
    'hero.modeValue': 'Hibrit',
    'hero.primaryCta': 'Bildiri Gönder',
    'hero.secondaryCta': 'Katılım Bilgileri',
    'countdown.label': 'Konferansa Kalan Süre',
    'countdown.days': 'Gün',
    'countdown.hours': 'Saat',
    'countdown.minutes': 'Dakika',
    'countdown.seconds': 'Saniye',
    'hero.infoBadge': 'Öne Çıkanlar',
    'hero.info1': 'Türkçe ve İngilizce bildiri kabulü',
    'hero.info2': 'ISBN’li bildiri kitabı',
    'hero.info3': 'İndeksli dergilerde yayın imkânı',
    'hero.info4': 'Akademi, sağlık, eğitim ve sosyal bilimlerden katılım',
    'about.kicker': 'Davet',
    'about.title': 'Konferans Hakkında',
    'about.text1': 'Yaşamın nicelik ve nitelik olarak anlamlı bir şekilde sürdürülmesi, varoluşumuzun temelini oluşturur. Bu bağlamda yaşam kalitesi, çok boyutlu ve disiplinlerarası bir içerikle ele alınmaktadır.',
    'about.text2': 'Konferans; bilim insanları, eğitmenler, öğretmenler, doktorlar, fizyoterapistler ve yaşam kalitesi, sağlık, spor, beslenme ve eğitim ortamıyla ilgilenen tüm katılımcılara açıktır.',
    'dates.kicker': 'Yer ve Önemli Tarihler',
    'dates.title': 'Takvim',
    'dates.venueTitle': 'Konferans Yeri',
    'dates.venueText': 'Çanakkale Onsekiz Mart Üniversitesi, Çanakkale Uygulamalı Bilimler Fakültesi Konferans Salonu',
    'dates.item1Date': '26/12/2025',
    'dates.item1Title': 'Özet Gönderim Son Tarihi',
    'dates.item2Date': '28/12/2025',
    'dates.item2Title': 'Kabul Edilen Bildirilerin İlanı',
    'dates.item3Date': '02/01/2026',
    'dates.item3Title': 'Kayıt İçin Son Tarih',
    'dates.item4Date': '04/01/2026',
    'dates.item4Title': 'Programın İlanı',
    'dates.item5Date': '30/01/2026',
    'dates.item5Title': 'Tam Metin Son Teslim Tarihi',
    'topics.kicker': 'Konular',
    'topics.title': 'Bildiri Alanları',
    'topics.1': 'Kavramsal tartışmalar',
    'topics.2': 'Yaşam kalitesinin ölçülmesi',
    'topics.3': 'Dijitalleşme ve yaşam kalitesi',
    'topics.4': 'Medya ve yaşam kalitesi',
    'topics.5': 'Ekonomi ve yaşam kalitesi',
    'topics.6': 'Eğitim ve yaşam kalitesi',
    'topics.7': 'Kültür, turizm ve yaşam kalitesi',
    'topics.8': 'Gıda, tarım ve yaşam kalitesi',
    'topics.9': 'Enerji ve yaşam kalitesi',
    'topics.10': 'Sağlık ve yaşam kalitesi',
    'topics.11': 'Spor ve yaşam kalitesi',
    'topics.12': 'Yaşanabilir şehirler',
    'topics.13': 'Hukuk ve yaşam kalitesi',
    'topics.14': 'Psikoloji ve yaşam kalitesi',
    'topics.15': 'Sanat ve yaşam kalitesi',
    'topics.16': 'Kamu hizmetleri ve yaşam kalitesi',
    'topics.17': 'Çevresel sorunlar ve yaşam kalitesi',
    'topics.18': 'Diğer ilgili konular',

    'topics.intro': 'Konferans, yaşam kalitesini çok boyutlu bir çerçevede ele alan disiplinlerarası araştırmaları bir araya getirir.',
    'topics.featuredLabel': 'Öne Çıkan İzlekler',
    'topics.featured1Title': 'Sağlık ve İyi Oluş',
    'topics.featured1Text': 'Sağlık, psikoloji, spor ve iyi oluş ekseninde insan yaşamını güçlendiren çalışmalar.',
    'topics.featured2Title': 'Dijital Yaşam',
    'topics.featured2Text': 'Dijitalleşme, medya ve veri odaklı yaşam pratiklerinin yaşam kalitesine etkileri.',
    'topics.featured3Title': 'Sürdürülebilir Şehirler',
    'topics.featured3Text': 'Şehir, çevre, enerji ve kamu hizmetleri perspektifinden sürdürülebilir yaşam alanları.',
    'topics.featured4Title': 'Kültür ve Toplum',
    'topics.featured4Text': 'Eğitim, kültür, sanat, hukuk ve toplumsal yaşam ilişkileri üzerine çalışmalar.',
    'topics.1desc': 'Yaşam kalitesi kavramının kuramsal çerçevesi, tanımları ve disiplinlerarası tartışmaları.',
    'topics.2desc': 'Ölçekler, göstergeler, veri toplama modelleri ve değerlendirme yaklaşımları.',
    'topics.3desc': 'Dijital dönüşüm, çevrimiçi yaşam, teknoloji kullanımı ve dijital refah başlıkları.',
    'topics.4desc': 'İletişim ortamları, medya tüketimi ve toplumsal algı süreçlerinin yaşam kalitesine etkisi.',
    'topics.5desc': 'Gelir, istihdam, refah ekonomisi ve ekonomik eşitsizliklerin yaşam deneyimine etkileri.',
    'topics.6desc': 'Öğrenme ortamları, eğitim politikaları ve bireysel gelişim bağlamında yaşam kalitesi.',
    'topics.7desc': 'Kültürel üretim, deneyim ekonomisi ve turizm hareketliliği ile yaşam memnuniyeti ilişkisi.',
    'topics.8desc': 'Beslenme, gıda güvenliği, tarımsal üretim ve sürdürülebilir yaşam pratikleri.',
    'topics.9desc': 'Enerji erişimi, verimlilik, sürdürülebilirlik ve yaşam standartları arasındaki bağlar.',
    'topics.10desc': 'Fiziksel, ruhsal ve toplumsal sağlık göstergeleri ile yaşam doyumu arasındaki ilişkiler.',
    'topics.11desc': 'Hareket, fiziksel aktivite, spor kültürü ve sağlıklı yaşam davranışları.',
    'topics.12desc': 'Kentsel tasarım, ulaşım, güvenlik, erişilebilirlik ve kent yaşamı deneyimleri.',
    'topics.13desc': 'Haklar, adalet, eşitlik ve hukuki düzenlemelerin yaşam kalitesi üzerindeki rolü.',
    'topics.14desc': 'Bireysel iyi oluş, duygu durum, psikososyal süreçler ve yaşam memnuniyeti çalışmaları.',
    'topics.15desc': 'Sanatsal ifade, estetik deneyim ve yaratıcı üretimin yaşam kalitesine katkısı.',
    'topics.16desc': 'Sosyal politika, kamu yönetimi ve hizmet kalitesi üzerinden toplumsal yaşamın iyileştirilmesi.',
    'topics.17desc': 'İklim, çevre, ekolojik denge ve sürdürülebilir gelecek perspektifleri.',
    'topics.18desc': 'Yaşam kalitesi ile bağlantılı özgün, yeni ve disiplinlerarası çalışma alanları.',
    'topics.calloutTag': 'Bildiri Çağrısı',
    'topics.calloutTitle': 'Disiplinlerarası bildiriler memnuniyetle kabul edilir',
    'topics.calloutText': 'Yaşam kalitesiyle ilişkili özgün, eleştirel ve uygulamalı çalışmalarınızı bekliyoruz.',
    'publication.kicker': 'Yayın Olanakları',
    'publication.title': 'Sunulan Bildiriler İçin Seçenekler',
    'publication.box1Title': 'Bildiri Kitabı',
    'publication.box1Text': 'Sunulan bildiriler ISBN’li e-kitap olarak yayımlanacaktır.',
    'publication.box2Title': 'Editoryal Kitap',
    'publication.box2Text': 'İsteyen yazarlar çalışmalarını alanlarına uygun ISBN’li ve bandrollü editoryal kitapta bölüm olarak yayımlatabilir. Ücret: makale başına 50 USD.',
    'publication.box3Title': 'İndeksli Dergiler',
    'publication.box3Text': 'Uygun bulunan çalışmalar, dergi kurullarının değerlendirmesi sonrası uluslararası hakemli ve indeksli Holistence Academy dergilerinde yayımlanabilir.',
    'registration.kicker': 'Katılım',
    'registration.title': 'Kayıt ve Ödeme Bilgileri',
    'registration.price1Title': 'Online Katılım',
    'registration.price2Title': 'Yüz Yüze Sunum',
    'registration.price3Title': 'Öğrenci Katılımı',
    'registration.price3Note': 'Lisans ve yüksek lisans öğrencileri için yüz yüze katılım ücreti.',
    'registration.priceNote': 'Ücretler bildiri başına alınmaktadır.',
    'registration.bankTitle': 'Kayıt ve Ödeme',
    'registration.bankNameLabel': 'Hesap Adı:',
    'registration.bankNameValue': 'Yaşam Kalitesi Derneği',
    'registration.bankBranchLabel': 'Banka / Şube:',
    'registration.bankBranchValue': 'Ziraat Bankası Kordon Şubesi',
    'registration.bankReceipt': 'Dekontunuzu e-posta ile veya WhatsApp üzerinden iletebilirsiniz.',
    'registration.bankNote': 'Önemli not: Ödeme açıklamasına adınız ve “Derneğe Bağış” ifadesi yazılmalıdır.',
    'boards.kicker': 'Kurullar',
    'boards.title': 'Akademik Yapı',
    'boards.presidentTitle': 'Konferans Başkanı',
    'boards.advisoryTitle': 'Danışma Kurulu',
    'boards.organizingTitle': 'Düzenleme Kurulu',
    'boards.scientificTitle': 'Bilim Kurulu',
    'boards.scientificIntro': 'Aşağıda kurulun öne çıkan üyelerinden bir seçki yer almaktadır.',
    'rules.kicker': 'Yazım Kuralları',
    'rules.title': 'Özet ve Tam Metin Kuralları',
    'rules.abstractTitle': 'Özet Yazım Kuralları',
    'rules.abstractText': 'Özetler tam metin kurallarına uygun, amaç ve kapsamı yansıtan, yöntem ve bulguları içeren biçimde hazırlanmalıdır. En az 200, en fazla 300 sözcük olmalı; 3 ila 5 anahtar kelime içermelidir. Türkçe bildirilerde İngilizce başlık ve özet de eklenmelidir.',
    'rules.fullTextTitle': 'Tam Metin Kuralları',
    'rules.fullTextText': 'Tam metinler, konferansın yayımladığı şablon dosyasına uygun hazırlanmalıdır. Dergi veya editoryal kitap başvurularında ilgili yayının kendi yazım kuralları esas alınır.',
    'rules.templateLink': 'Şablon Dosyasını Aç',
    'contact.kicker': 'İletişim',
    'contact.title': 'Bize Ulaşın',
    'footer.backToTop': 'Yukarı Dön'
  },
  en: {
    'nav.about': 'About',
    'nav.dates': 'Important Dates',
    'nav.topics': 'Topics',
    'nav.publication': 'Publication',
    'nav.registration': 'Registration',
    'nav.boards': 'Boards',
    'nav.rules': 'Writing Rules',
    'nav.contact': 'Contact',
    'hero.eyebrow': 'Hybrid Academic Conference',
    'hero.title': 'III. International Quality of Life Conference',
    'hero.subtitle': 'An international conference addressing quality of life through an interdisciplinary lens and welcoming papers in Turkish and English.',
    'hero.dateLabel': 'Date',
    'hero.dateValue': '16–17 January 2026',
    'hero.locationLabel': 'Venue',
    'hero.locationValue': 'Çanakkale / Türkiye',
    'hero.modeLabel': 'Format',
    'hero.modeValue': 'Hybrid',
    'hero.primaryCta': 'Send Paper',
    'hero.secondaryCta': 'Registration Info',
    'countdown.label': 'Time Left to Conference',
    'countdown.days': 'Days',
    'countdown.hours': 'Hours',
    'countdown.minutes': 'Minutes',
    'countdown.seconds': 'Seconds',
    'hero.infoBadge': 'Highlights',
    'hero.info1': 'Turkish and English paper submissions',
    'hero.info2': 'ISBN-registered proceedings book',
    'hero.info3': 'Opportunity for indexed journal publication',
    'hero.info4': 'Participants from academia, health, education, and social sciences',
    'about.kicker': 'Call For Papers',
    'about.title': 'About the Conference',
    'about.text1': 'Maintaining a meaningful life in terms of both quantity and quality forms the basis of our existence. In this context, quality of life emerges as a multidimensional and interdisciplinary concept.',
    'about.text2': 'The conference welcomes scientists, trainers, teachers, doctors, physiotherapists, and everyone interested in quality of life, health, sports, nutrition, and educational environments.',
    'dates.kicker': 'Venue & Important Dates',
    'dates.title': 'Conference Timeline',
    'dates.venueTitle': 'Venue',
    'dates.venueText': 'Conference Hall of Çanakkale Onsekiz Mart University, Çanakkale Faculty of Applied Sciences',
    'dates.item1Date': '26/12/2025',
    'dates.item1Title': 'Deadline for Abstract Submission',
    'dates.item2Date': '28/12/2025',
    'dates.item2Title': 'Announcement of Accepted Papers',
    'dates.item3Date': '02/01/2026',
    'dates.item3Title': 'Deadline for Registration',
    'dates.item4Date': '04/01/2026',
    'dates.item4Title': 'Conference Program Announcement',
    'dates.item5Date': '30/01/2026',
    'dates.item5Title': 'Deadline for Full Text Submission',
    'topics.kicker': 'Topics',
    'topics.title': 'Conference Topics',
    'topics.1': 'Conceptual debates',
    'topics.2': 'Measurement of quality of life',
    'topics.3': 'Digitalization and quality of life',
    'topics.4': 'Media and quality of life',
    'topics.5': 'Economy and quality of life',
    'topics.6': 'Education and quality of life',
    'topics.7': 'Culture, tourism and quality of life',
    'topics.8': 'Food, agriculture and quality of life',
    'topics.9': 'Energy and quality of life',
    'topics.10': 'Health and quality of life',
    'topics.11': 'Sport and quality of life',
    'topics.12': 'Livable cities',
    'topics.13': 'Law and quality of life',
    'topics.14': 'Psychology and quality of life',
    'topics.15': 'Arts and quality of life',
    'topics.16': 'Public services and quality of life',
    'topics.17': 'Environmental issues and quality of life',
    'topics.18': 'Other related topics',

    'topics.intro': 'The conference brings together interdisciplinary research addressing quality of life through a multidimensional perspective.',
    'topics.featuredLabel': 'Featured Tracks',
    'topics.featured1Title': 'Health & Wellbeing',
    'topics.featured1Text': 'Research that strengthens human life through health, psychology, sport, and wellbeing.',
    'topics.featured2Title': 'Digital Life',
    'topics.featured2Text': 'The effects of digitalization, media, and data-driven living practices on quality of life.',
    'topics.featured3Title': 'Sustainable Cities',
    'topics.featured3Text': 'Sustainable living environments from the perspective of cities, environment, energy, and public services.',
    'topics.featured4Title': 'Culture & Society',
    'topics.featured4Text': 'Studies on education, culture, arts, law, and the dynamics of social life.',
    'topics.1desc': 'Theoretical frameworks, definitions, and interdisciplinary debates around the concept of quality of life.',
    'topics.2desc': 'Scales, indicators, data collection models, and evaluation approaches.',
    'topics.3desc': 'Digital transformation, online life, technology use, and digital wellbeing.',
    'topics.4desc': 'The impact of communication environments, media consumption, and social perception processes on quality of life.',
    'topics.5desc': 'The effects of income, employment, welfare economics, and inequality on lived experience.',
    'topics.6desc': 'Quality of life in relation to learning environments, education policies, and personal development.',
    'topics.7desc': 'The relationship between cultural production, experience economy, tourism mobility, and life satisfaction.',
    'topics.8desc': 'Nutrition, food security, agricultural production, and sustainable living practices.',
    'topics.9desc': 'Links among energy access, efficiency, sustainability, and living standards.',
    'topics.10desc': 'Relationships between physical, mental, and social health indicators and life satisfaction.',
    'topics.11desc': 'Movement, physical activity, sport culture, and healthy lifestyle behaviours.',
    'topics.12desc': 'Urban design, mobility, safety, accessibility, and city life experiences.',
    'topics.13desc': 'The role of rights, justice, equality, and legal regulations in quality of life.',
    'topics.14desc': 'Studies on individual wellbeing, mood, psychosocial processes, and life satisfaction.',
    'topics.15desc': 'The contribution of artistic expression, aesthetic experience, and creative production to quality of life.',
    'topics.16desc': 'Improving social life through social policy, public administration, and service quality.',
    'topics.17desc': 'Climate, environment, ecological balance, and sustainable futures.',
    'topics.18desc': 'Original, emerging, and interdisciplinary areas related to quality of life.',
    'topics.calloutTag': 'Call for Papers',
    'topics.calloutTitle': 'Interdisciplinary submissions are welcome',
    'topics.calloutText': 'We welcome original, critical, and practice-based studies related to quality of life.',
    'publication.kicker': 'Publication Possibilities',
    'publication.title': 'Options for Presented Papers',
    'publication.box1Title': 'Proceedings Book',
    'publication.box1Text': 'Presented papers will be published as an ISBN-registered e-book.',
    'publication.box2Title': 'Editorial Book Chapter',
    'publication.box2Text': 'Authors may publish their work as a chapter in an ISBN-registered editorial book relevant to their field. Fee: 50 USD per article.',
    'publication.box3Title': 'Indexed Journals',
    'publication.box3Text': 'Eligible papers may be published in international peer-reviewed and indexed Holistence Academy journals after editorial review.',
    'registration.kicker': 'Registration',
    'registration.title': 'Registration & Payment',
    'registration.price1Title': 'Online Participation',
    'registration.price2Title': 'Face-to-Face Presentation',
    'registration.price3Title': 'Student Participation',
    'registration.price3Note': 'Face-to-face participation fee for undergraduate and graduate students.',
    'registration.priceNote': 'Fees are charged per paper.',
    'registration.bankTitle': 'Registration and Payment',
    'registration.bankNameLabel': 'Account Name:',
    'registration.bankNameValue': 'Yaşam Kalitesi Derneği',
    'registration.bankBranchLabel': 'Bank / Branch:',
    'registration.bankBranchValue': 'Ziraat Bankası Kordon Branch',
    'registration.bankReceipt': 'You may send your receipt by email or via WhatsApp.',
    'registration.bankNote': 'Important note: Add your name and the phrase “Donation to the Association” in the payment description.',
    'boards.kicker': 'Boards',
    'boards.title': 'Academic Structure',
    'boards.presidentTitle': 'Conference President',
    'boards.advisoryTitle': 'Advisory Board',
    'boards.organizingTitle': 'Organizing Committee',
    'boards.scientificTitle': 'Scientific Board',
    'boards.scientificIntro': 'Below is a selected list of members from the scientific board.',
    'rules.kicker': 'Writing Rules',
    'rules.title': 'Abstract & Full Text Rules',
    'rules.abstractTitle': 'Abstract Writing Rules',
    'rules.abstractText': 'Abstracts should follow the full-text rules, reflect purpose and scope, and include method and findings. They should contain 200–300 words and 3 to 5 keywords. Turkish papers must also include an English title and abstract.',
    'rules.fullTextTitle': 'Full Text Rules',
    'rules.fullTextText': 'Full texts should be prepared according to the conference template file. For journal or editorial book publication, the corresponding publication guidelines apply.',
    'rules.templateLink': 'Open Template File',
    'contact.kicker': 'Contact',
    'contact.title': 'Get in Touch',
    'footer.backToTop': 'Back to Top'
  }
};

const html = document.documentElement;
const buttons = document.querySelectorAll('.lang-btn');
const translatable = document.querySelectorAll('[data-i18n]');

function setLanguage(lang) {
  html.lang = lang;
  localStorage.setItem('iqlc-lang', lang);
  buttons.forEach(btn => btn.classList.toggle('active', btn.dataset.setlang === lang));
  translatable.forEach(el => {
    const key = el.dataset.i18n;
    if (translations[lang]?.[key]) el.textContent = translations[lang][key];
  });
}

buttons.forEach(btn => btn.addEventListener('click', () => setLanguage(btn.dataset.setlang)));
setLanguage(localStorage.getItem('iqlc-lang') || 'tr');

const menuToggle = document.querySelector('.menu-toggle');
const navLinks = document.querySelector('.nav-links');
menuToggle?.addEventListener('click', () => navLinks.classList.toggle('open'));
navLinks?.querySelectorAll('a').forEach(link => link.addEventListener('click', () => navLinks.classList.remove('open')));

const targetDate = new Date('2026-01-16T09:00:00+03:00').getTime();
const countdownIds = { days: 'days', hours: 'hours', minutes: 'minutes', seconds: 'seconds' };

function updateCountdown() {
  const now = Date.now();
  const distance = targetDate - now;
  if (distance <= 0) {
    Object.values(countdownIds).forEach(id => document.getElementById(id).textContent = '00');
    return;
  }
  const values = {
    days: Math.floor(distance / (1000 * 60 * 60 * 24)),
    hours: Math.floor((distance / (1000 * 60 * 60)) % 24),
    minutes: Math.floor((distance / (1000 * 60)) % 60),
    seconds: Math.floor((distance / 1000) % 60)
  };
  for (const [key, value] of Object.entries(values)) {
    document.getElementById(countdownIds[key]).textContent = String(value).padStart(2, '0');
  }
}
updateCountdown();
setInterval(updateCountdown, 1000);

const observer = new IntersectionObserver(entries => {
  entries.forEach(entry => {
    if (entry.isIntersecting) entry.target.classList.add('visible');
  });
}, { threshold: 0.14 });

document.querySelectorAll('.reveal').forEach(el => observer.observe(el));
